# Generated by Django 6.0.1 on 2026-01-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'verbose_name': 'Test attempt', 'verbose_name_plural': 'Test attempts'},
        ),
        migrations.AlterModelOptions(
            name='userresponse',
            options={'verbose_name': 'User response', 'verbose_name_plural': 'User responses'},
        ),
        migrations.AddField(
            model_name='choice',
            name='text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Choice text'),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Choice text'),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Choice text'),
        ),
        migrations.AddField(
            model_name='module',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Module title'),
        ),
        migrations.AddField(
            model_name='module',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Module title'),
        ),
        migrations.AddField(
            model_name='module',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Module title'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Subject name'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Subject name'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Subject name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is correct'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Choice text'),
        ),
        migrations.AlterField(
            model_name='module',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='quiz.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Module title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question text'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='fas fa-code', help_text='FontAwesome icon class', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subject name'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed at'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='total_questions',
            field=models.IntegerField(default=20, verbose_name='Total questions'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.testattempt', verbose_name='Test attempt'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is correct'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice', verbose_name='Selected choice'),
        ),
    ]
